version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5940:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./database-volume:/var/lib/postgresql/data:rw

  node-runner:
    container_name: node-runner
    image: node:22.14.0-alpine
    working_dir: /home/node/app
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    tmpfs:
      - /var/lib/postgresql/data
    command: sh -c "npm ci && npm run build && npm run test:e2e --runInBand"
