version: "3.9"

services:
  node-runner:
    container_name: node-runner
    image: node:22.14.0-alpine
    working_dir: /home/node/app
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - ./:/home/node/app
      - ./node_modules/:/home/node/app/node_modules
    command: /bin/true
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database-volume:/var/lib/postgresql/data:rw
    ports:
      - "5940:5432"

volumes:
  database-volume:
