version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5940:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  node-runner:
    container_name: node-runner
    image: node:22.14.0-alpine
    working_dir: /home/node/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      PORT: 3000
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    command: /bin/true
    depends_on:
      - postgres